name: Quality assurance
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'composer.json'
      - '**.php'
  push:
    paths:
      - 'composer.json'
      - '**.php'
jobs:
  lint-php:
      strategy:
        matrix:
          php: ["8.1", "8.2", "8.3"]
      uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
      with:
        PHP_VERSION: ${{ matrix.php }}

  static-code-analysis-backend:
    uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main

  php-unit-tests:
    uses: inpsyde/reusable-workflows/.github/workflows/tests-unit-php.yml@main
    strategy:
      matrix:
        php: ["8.1", "8.2"]
    with:
      PHP_VERSION: ${{ matrix.php }}
